- name: Ensure homebrew packages are installed
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_packages }}"

- name: Pull the dotfiles repo
  ansible.builtin.git:
    repo: "{{ dotfile_git_url }}"
    dest: ~/.dotfiles
    update: yes
  when: dotfile_git_url
