- name: Ensure homebrew packages are installed
  community.general.homebrew:
    name: "{{ item }}"
    state: present
  with_items: "{{ homebrew_packages }}"

- name: Pull the dotfiles repo
  ansible.builtin.git:
    repo: "{{ dotfile_git_url }}"
    dest: ~/.dotfiles
    update: yes
  when: dotfile_git_url

- name: Find stowable directories in dotfiles repo
  ansible.builtin.find:
    paths: "{{ ansible_env.HOME }}/.dotfiles"
    file_type: directory
    depth: 1
  register: dotfile_dirs
  when: dotfile_git_url

- name: Stow dotfiles
  ansible.builtin.command: "stow {{ item.path | basename }} -v2"
  args:
    chdir: "{{ ansible_env.HOME }}/.dotfiles"
  loop: "{{ dotfile_dirs.files }}"
  register: stow_output
  changed_when: "'LINK' in stow_output.stderr" 
  when: dotfile_git_url