#SPDX-License-Identifier: MIT-0
---
# tasks file for sre-tooling
- name: Ping machine to ensure availability
  ansible.builtin.ping:

- name: Run lenvo config
  include_tasks: lenovo_os.yml
  when: ansible_os_family == "RedHat"

- name: Run mac config
  include_tasks: mac_os.yml
  when: ansible_os_family == "Darwin"
